# Generated by Django 3.0.5 on 2020-04-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200422_1605'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
