# Generated by Django 3.0.5 on 2020-04-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_delete_postlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
    ]
