# Generated by Django 3.0.5 on 2020-04-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200426_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='login_username',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
