# Generated by Django 3.0.5 on 2020-04-28 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20200428_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequestactivitylog',
            name='path_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userrequestactivitylog',
            name='request_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userrequestactivitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_activity', to=settings.AUTH_USER_MODEL),
        ),
    ]
